/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  about: () => import("@/views/about/index.vue"),
  alova_request: () => import("@/views/alova/request/index.vue"),
  alova_scenes: () => import("@/views/alova/scenes/index.vue"),
  alova_user: () => import("@/views/alova/user/index.vue"),
  dashboard: () => import("@/views/dashboard/index.vue"),
  "data-asset_data-model": () => import("@/views/data-asset/data-model/index.vue"),
  "data-asset_database": () => import("@/views/data-asset/database/index.vue"),
  "data-asset_tag-settings": () => import("@/views/data-asset/tag-settings/index.vue"),
  "data-service_api-manange": () => import("@/views/data-service/api-manange/index.vue"),
  "data-service_application": () => import("@/views/data-service/application/index.vue"),
  "decision-detail": () => import("@/views/decision-detail/[id].vue"),
  decision: () => import("@/views/decision/index.vue"),
  "function_hide-child_one": () => import("@/views/function/hide-child/one/index.vue"),
  "function_hide-child_three": () => import("@/views/function/hide-child/three/index.vue"),
  "function_hide-child_two": () => import("@/views/function/hide-child/two/index.vue"),
  "function_multi-tab": () => import("@/views/function/multi-tab/index.vue"),
  function_request: () => import("@/views/function/request/index.vue"),
  "function_super-page": () => import("@/views/function/super-page/index.vue"),
  function_tab: () => import("@/views/function/tab/index.vue"),
  "function_toggle-auth": () => import("@/views/function/toggle-auth/index.vue"),
  home: () => import("@/views/home/index.vue"),
  manage_api: () => import("@/views/manage/api/index.vue"),
  manage_log: () => import("@/views/manage/log/index.vue"),
  manage_menu: () => import("@/views/manage/menu/index.vue"),
  "manage_notification-settings": () => import("@/views/manage/notification-settings/index.vue"),
  "manage_notification-tpls": () => import("@/views/manage/notification-tpls/index.vue"),
  manage_role: () => import("@/views/manage/role/index.vue"),
  "manage_user-detail": () => import("@/views/manage/user-detail/[id].vue"),
  manage_user: () => import("@/views/manage/user/index.vue"),
  "metric-ai": () => import("@/views/metric-ai/[id].vue"),
  "metric-detail": () => import("@/views/metric-detail/[id].vue"),
  "metric-exploration": () => import("@/views/metric-exploration/[id].vue"),
  "metric-publish": () => import("@/views/metric-publish/[id].vue"),
  "metric-report": () => import("@/views/metric-report/[id].vue"),
  metric: () => import("@/views/metric/index.vue"),
  plugin_barcode: () => import("@/views/plugin/barcode/index.vue"),
  plugin_charts_antv: () => import("@/views/plugin/charts/antv/index.vue"),
  plugin_charts_echarts: () => import("@/views/plugin/charts/echarts/index.vue"),
  plugin_copy: () => import("@/views/plugin/copy/index.vue"),
  plugin_editor_markdown: () => import("@/views/plugin/editor/markdown/index.vue"),
  plugin_editor_quill: () => import("@/views/plugin/editor/quill/index.vue"),
  plugin_excel: () => import("@/views/plugin/excel/index.vue"),
  plugin_gantt: () => import("@/views/plugin/gantt/index.vue"),
  plugin_icon: () => import("@/views/plugin/icon/index.vue"),
  plugin_map: () => import("@/views/plugin/map/index.vue"),
  plugin_pdf: () => import("@/views/plugin/pdf/index.vue"),
  plugin_pinyin: () => import("@/views/plugin/pinyin/index.vue"),
  plugin_print: () => import("@/views/plugin/print/index.vue"),
  plugin_swiper: () => import("@/views/plugin/swiper/index.vue"),
  plugin_typeit: () => import("@/views/plugin/typeit/index.vue"),
  plugin_video: () => import("@/views/plugin/video/index.vue"),
  report: () => import("@/views/report/index.vue"),
  task: () => import("@/views/task/index.vue"),
  "user-center": () => import("@/views/user-center/index.vue"),
};
